config/routes.rb
Rails.application.routes.draw do

  root to:"starter#index"
  resources :starter, only: [:index, :new, :create]
  resources :users

  # Application routes
  namespace :app do
    root to: "dashboard#index"
    get '/login', to: "sessions#new", as: :login
    post '/login', to: "sessions#create"
    get 'profil', to: "sessions#show", as: :profil
    post 'logout', to: "sessions#destroy", as: :logout

    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'settings', to: 'settings#edit', as: :settings
    patch 'settings', to: 'settings#update'

    resources :posts, :events
    resources :connecteds, only: [:index, :create, :update, :destroy]
    resources :collects do
      member do
        post "contribute", to: "collects#contribute", as: :contribution
      end
    end
    
    
    resources :children
    # Group and members
    resources :groups do
      member do
        post "add-members", to: "groups#add_members", as: :add_members_to
        get "eject-member/:user_id", to: "groups#eject_member", as: :eject_member_from
      end
    end
    
    resources :faithfuls do
      member do
        get "approve", to: "faithfuls#approve", as: :approve
        get "eject", to: "faithfuls#eject", as: :eject
      end
    end
  end


  # faithful user routes
  namespace :me, only: [:index, :show, :update] do
    root to: 'posts#index'
    resources :posts do
      member do
        patch 'like', to: "posts#like", as: :like
        patch 'comment', to: 'posts#comment', as: :comment
        patch 'favorite', to: 'posts#favorite', as: :favorite
      end
    end
    get '/calendar', to: 'posts#calendar', as: :calendar
    get '/favorites', to: 'posts#favorites', as: :favorites

    resources :groups, only: [:show, :update]
  end


  namespace :admin do
    resources :churches
  end


  mount Pwa::Engine, at: ''

end

app/controllers/starter_controller.rb
class StarterController < ApplicationController
  skip_before_action :only_login_in

  def index
  end

  def new
  end

  def create
    
  end
end

app/views/layouts/templates/starter/_admin_sidebar.html.erb
<li class="nav-header">ADMINISTRATION</li>
<% if current_user.managed_church? %>
<li class="nav-item">
  <a href="<%=app_children_path%>" data-turbolinks="false" class="nav-link <%= 'active' if content_for?(:page_name) and content_for(:page_name) == 'view.childs' %>">
    <i class="nav-icon fas fa-archive"></i>
    <p>
      Stations
    </p>
  </a>
</li>

<li class="nav-item">
  <a href="<%=app_children_path%>" data-turbolinks="false" class="nav-link <%= 'active' if content_for?(:page_name) and content_for(:page_name) == 'view.admin_faithfuls' %>">
    <i class="nav-icon fas fa-users"></i>
    <p>
      Fidèles
    </p>
  </a>
</li>

<li class="nav-item">
  <a href="<%=app_children_path%>" data-turbolinks="false" class="nav-link <%= 'active' if content_for?(:page_name) and content_for(:page_name) == 'view.childs' %>">
    <i class="nav-icon fas fa-archive"></i>
    <p>
      Plaintes
    </p>
  </a>
</li>

<li class="nav-item">
  <a href="<%=app_connecteds_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.connecteds' %>">
    <i class="nav-icon fas fa-usd"></i>
    <p>
      Abonnés
    </p>
  </a>
</li>
<% end %>


<!-- Manager d'eglise -->
<% if current_user.managed_church? %>
<li class="nav-item">
  <a href="<%=app_settings_path%>" class="nav-link <%= 'active' if content_for?(:page_name) and content_for(:page_name) == 'view.settings' %>">
    <i class="nav-icon fas fa-cog"></i>
    <p>
      Configurations
    </p>
  </a>
</li>
<% end %>

app/views/layouts/templates/starter/_app_sidebar.html.erb
<li class="nav-header">STATION</li>

<!-- 
<li class="nav-item ">
  <a href="<%=app_dashboard_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-tachometer-alt"></i>
    <p>
      Dashboard
    </p>
  </a>
</li>
-->

<li class="nav-item">
  <a href="<%=app_faithfuls_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.faithfuls' %>">
    <i class="nav-icon fas fa-database"></i>
    <p>
      Fidèles
    </p>
  </a>
</li>

<% if current_user.managed_child? %>
<li class="nav-item">
  <a href="<%=app_groups_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.groups' %>">
    <i class="nav-icon fas fa-users"></i>
    <p>
      Groupes
    </p>
  </a>
</li>



<li class="nav-item">
  <a href="<%=app_posts_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.posts' %>">
    <i class="nav-icon fas fa-bullhorn"></i>
    <p>
      Publications
    </p>
  </a>
</li>

<li class="nav-item">
  <a href="<%=app_events_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.events' %>">
    <i class="nav-icon fas fa-calendar"></i>
    <p>
      Evenements
    </p>
  </a>
</li>

<li class="nav-item">
  <a href="<%=app_collects_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.collects' %>">
    <i class="nav-icon fas fa-usd"></i>
    <p>
      Collèctes
    </p>
  </a>
</li>


<!--
<li class="nav-item">
  <a href="<%=app_connecteds_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.connecteds' %>">
    <i class="nav-icon fas fa-usd"></i>
    <p>
      Sondages
    </p>
  </a>
</li> 
-->

<% end %>

app/views/layouts/templates/starter/_body.html.erb
<%= render 'layouts/templates/starter/navbar' %>
<%= render 'layouts/templates/starter/sidebar' %>





<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">Dashboard</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v1</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
    
      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">
          <%= yield %>
        </section>
        <!-- /.Left col -->
        <%= render "layouts/templates/plugins/toastr" %>
      </div>
      <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>

app/views/layouts/templates/starter/_includes.html.erb
<!-- Global stylesheet's -->
<%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" %>
<%= stylesheet_link_tag "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/fontawesome-free/css/all.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/dist/css/adminlte.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/daterangepicker/daterangepicker.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/summernote/summernote-bs4.min.css" %>
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/toastr/toastr.min.css" %>
<!-- Font Awesome -->
<%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/fontawesome-free/css/all.min.css" %>


<!-- Global javascript -->
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/jquery/jquery.min.js" %>
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/jquery-ui/jquery-ui.min.js" %>
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/bootstrap/js/bootstrap.bundle.min.js" %>
<!-- daterangepicker -->
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/daterangepicker/daterangepicker.js" %>
<!-- Tempusdominus Bootstrap 4 -->
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %>
<!-- Summernote -->
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/summernote/summernote-bs4.min.js" %>
<!-- overlayScrollbars -->
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %>
<%= javascript_include_tag asset_url "/templates/adminLte/plugins/toastr/toastr.min.js" %>
<!-- AdminLTE App -->
<%= javascript_include_tag asset_url "/templates/adminLte/dist/js/adminlte.js" %>


<% if request.path.starts_with?('/app')  %>
  <!-- DataTables -->
  <%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" %>
  <%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" %>
  <%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/datatables-buttons/css/buttons.bootstrap4.min.css" %>
  <!-- JQVMap -->
  <%= stylesheet_link_tag asset_url "/templates/adminLte/plugins/jqvmap/jqvmap.min.css" %>


  <!-- DataTable insertion -->
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables/jquery.dataTables.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-responsive/js/dataTables.responsive.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-responsive/js/responsive.bootstrap4.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-buttons/js/dataTables.buttons.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-buttons/js/buttons.bootstrap4.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/jszip/jszip.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/pdfmake/pdfmake.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/pdfmake/vfs_fonts.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-buttons/js/buttons.html5.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-buttons/js/buttons.print.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/datatables-buttons/js/buttons.colVis.min.js" %>
  <!-- ChartJS -->
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/chart.js/Chart.min.js" %>
  <!-- Sparkline -->
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/sparklines/sparkline.js" %>
  <!-- JQVMap -->
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/jqvmap/jquery.vmap.min.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/jqvmap/maps/jquery.vmap.usa.js" %>
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/jquery-knob/jquery.knob.min.js" %>
  <!-- jQuery Knob Chart -->
  <%= javascript_include_tag asset_url "/templates/adminLte/plugins/moment/moment.min.js" %>

<% elsif request.path.starts_with?('/me') %>
  <%= content_for :script do %>
    
  <% end %>
<% end %>   
      


      

      

<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="<%=root_url%>dist/js/demo.js"></script> -->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="<%=root_url%>dist/js/pages/dashboard.js"></script> -->
    

app/views/layouts/templates/starter/_navbar.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="<%=root_url%>dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="<%=root_url%>" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/layouts/templates/starter/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="<%= app_root_path %>" class="brand-link">
    <img src="<%= asset_url '/templates/adminLte/dist/img/AdminLTELogo.png' %>"" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light"> <%= Rails.application.config.site[:name] %> </span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="<%= asset_url '/templates/adminLte/dist/img/user2-160x160.jpg' %>" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block"> <%= current_user.fullname %> </a>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <div class="form-inline">
      <div class="input-group" data-widget="sidebar-search">
        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-sidebar">
            <i class="fas fa-search fa-fw"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        
        <!-- Church manager items -->
        <% if current_user.managed_church? %>
          <%= render 'layouts/templates/starter/admin_sidebar' %>
        <% end %>
        <!-- Child manager items -->
        <% if current_user.managed_child? %>
          <%= render 'layouts/templates/starter/app_sidebar' %>
        <% end %>
        <!-- Child manager items -->
        <%= render 'layouts/templates/starter/user_sidebar' %>
        
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/layouts/templates/starter/_user_sidebar.html.erb
<li class="nav-header">FIDELE</li>

<li class="nav-item ">
  <a href="<%=me_root_path%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-database"></i>
    <p>
      Explorer
    </p>
  </a>
</li>
<!-- Groupes -->

<% if current_user.groups.present? %>
  <li class="nav-item">
    <a href="#" class="nav-link">
      <i class="nav-icon fas fa-users"></i>
      <p>
        Groupes
        <i class="right fas fa-angle-left"></i>
      </p>
    </a>
    <ul class="nav nav-treeview">
      <% current_user.groups.each do |group| %>
        <li class="nav-item">
          <a href="<%= me_group_path(group) %>" class="nav-link">
            <i class="far fa-circle nav-icon"></i>
            <%= content_tag 'p', group.acronym %>
          </a>
        </li>
      <% end %>
    </ul>
  </li>
<% end %>



<!-- Publications -->
<li class="nav-item ">
  <a href="<%=me_posts_path(type: :post)%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-bullhorn"></i>
    <p>
      Publications
    </p>
  </a>
</li>
<!-- Events -->
<li class="nav-item ">
  <a href="<%=me_posts_path(type: :event)%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-file"></i>
    <p>
      Evènements
    </p>
  </a>
</li>
<!-- Collectes -->
<li class="nav-item ">
  <a href="<%=me_posts_path(type: :collecte)%>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-pie-chart"></i>
    <p>
      Collectes
    </p>
  </a>
</li>
<!-- Calendrier -->
<li class="nav-item ">
  <a href="<%= me_calendar_path %>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-calendar"></i>
    <p>
      Calendrier
    </p>
  </a>
</li>
<!-- Favorites -->
<li class="nav-item ">
  <a href="<%= me_favorites_path %>" data-turbolinks="false" class="nav-link <%= "active" if content_for?(:page_name) and content_for(:page_name) == 'view.dashboard' %>">
    <i class="nav-icon fas fa-heart"></i>
    <p>
      Favories
    </p>
  </a>
</li>

app/views/layouts/templates/starter/index.html.erb
<% content_for :noapp, true %>

<%= content_for :header %>

<%= content_for :content %>

<%= content_for :footer %>

app/views/layouts/templates/starter/manager.html.erb
<% content_for :styles do %>
  
<% end %>

<% content_for :script do %>

<% end %>