config/routes.rb
Rails.application.routes.draw do

  root to:"starter#index"
  resources :starter, only: [:index, :new, :create]
  resources :users

  # Application routes
  namespace :app do
    root to: "dashboard#index"
    get '/login', to: "sessions#new", as: :login
    post '/login', to: "sessions#create"
    get 'profil', to: "sessions#show", as: :profil
    post 'logout', to: "sessions#destroy", as: :logout

    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'settings', to: 'settings#edit', as: :settings
    patch 'settings', to: 'settings#update'

    resources :posts, :events
    resources :connecteds, only: [:index, :create, :update, :destroy]
    resources :collects do
      member do
        post "contribute", to: "collects#contribute", as: :contribution
      end
    end
    
    
    resources :children
    # Group and members
    resources :groups do
      member do
        post "add-members", to: "groups#add_members", as: :add_members_to
        get "eject-member/:user_id", to: "groups#eject_member", as: :eject_member_from
      end
    end
    
    resources :faithfuls do
      member do
        get "approve", to: "faithfuls#approve", as: :approve
        get "eject", to: "faithfuls#eject", as: :eject
      end
    end
  end


  # faithful user routes
  namespace :me, only: [:index, :show, :update] do
    root to: 'posts#index'
    resources :posts do
      member do
        patch 'like', to: "posts#like", as: :like
        patch 'comment', to: 'posts#comment', as: :comment
        patch 'favorite', to: 'posts#favorite', as: :favorite
      end
    end
    get '/calendar', to: 'posts#calendar', as: :calendar
    get '/favorites', to: 'posts#favorites', as: :favorites

    resources :groups, only: [:show, :update]
  end


  namespace :admin do
    resources :churches
  end


  mount Pwa::Engine, at: ''

end

app/models/app/event.rb
class App::Event < Post
  before_create :add_type
  default_scope { where(mark: Post.marks[:event]) }

  # private
  def add_type
    mark = Post.marks[:event]
  end
end

app/controllers/app/events_controller.rb
class App::EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  def index
    @events = current_user.managed_child.posts.mark_event
  end

  def show
  end

  def new
    @event = App::Event.new
  end

  def edit
  end

  def create
    @event = App::Event.new(event_params )
    @event.author = current_user
    @event.child = current_user.managed_child

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = App::Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:app_event)
      .permit(:title, :content, :marked_to, :unmarked_to,
        :thumb, :thumb_cache)
    end
end

app/views/app/events/_form.html.erb
<%= form_for event do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-12 form-group">
      <%= form.label :marked_to, "Date de l'évenement" %>
      <%= form.datetime_field :marked_to, class: "form-control" %>
    </div>
    <div class="col-md-6 col-sm-12 form-group">
      <%= form.label :unmarked_to, "Date de fin" %>
      <%= form.datetime_field :unmarked_to, class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :thumb, "Image en avant" %>
    <%= form.file_field :thumb, class: "form-control", required: false %>
    <%= form.hidden_field :thumb_cache %>
  </div>

  <div class="mt-2 ">
    <%= image_tag event.thumb.thumb.url, alt: 'thumbnail' if event.thumb.present? %>
  </div>

  <div class="text-right mt-3">
    <%= form.submit "Sauvegarder", class: "btn btn-primary text-white" %>
  </div>
<% end %>

<% content_for :page_name, 'view.posts' %>

app/views/app/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', app_events_path %>

app/views/app/events/index.html.erb
<div class="card">
  <div class="card-header">
    <h3>Liste des Evenements</h3>
  </div>
  <div class="card-body">
    <div class="row text-right">
      <div class="col-12">
        <%= link_to 'Nouveau Evenement', new_app_event_path, data: {turbolinks: false}, class: 'btn btn-primary btn-sm text-white mb-2' %>
      </div>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Titre</th>
          <th>Contenue</th>
          <th>Auteur</th>
          <th>Créé</th>
          <th>Date d'execution</th>
          <th>Actions</th>
          <th></th>
        </tr>
      </thead>
      
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.title.truncate(100) %></td>
            <td><%= event.content.truncate(200) %></td>
            <td><%= event.author.present? ? event.author.fullname : 'Aucun'%></td>
            <td><%=str_time(event.created_at) %></td>
            <td>
              <%= "#{event.marked_to.strftime("%d %b %Y")} 
              au 
              #{event.unmarked_to.strftime("%d %b %Y")}" %></td>
            <td>
              <%= link_to content_tag('i', 'Voir', class: "fa fa-eye"), app_event_path(event), class: 'btn btn-success btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Editer', class: "fa fa-pen"), edit_app_event_path(event), class: 'btn btn-primary btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Supprimer', class: "fa fa-trash"), app_event_path(event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs text-white mb-2' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>


<% content_for :page_name, 'view.events' %>

app/views/app/events/new.html.erb
<h1>New event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', app_events_path %>

app/views/app/events/show.html.erb
<div class="card card-success">
  <div class="card-body">
    <div class="row">
      <div class="offset-lg-1 offset-xl-2 col-md-12 col-lg-10 col-xl-8">
        <div class="card mb-2 bg-gradient">
          <img class="card-img-top" src="<%= @event.thumb? ? @event.thumb.thumbnail.url : asset_url('/templates/adminLte/img/event.jpeg')  %>" alt="Dist Photo 1">
          <div class="card-img-overlay d-flex flex-column justify-content-end">
            <h5 class="card-title text-primary text-white"> <%= @event.title %> </h5>
            <a href="#" class="text-white"> </a>
            <small class="card-text text-white pb-2 pt-1 text-right text-sm"><%= "Par #{@event.author.fullname} #{str_time(@event.created_at)}" %></small>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col text-sm">
              <%= content_tag('h6', "Debut: #{@event.marked_to.strftime("%d %b %Y")}", class: "text-sm") %>
            </div>
            <div class="col text-right">
              <%= content_tag('h6', "Fin: #{@event.unmarked_to.strftime("%d %b %Y")}", class: "text-sm") %>
            </div>
          </div>
          <%= markdown(@event.content) %>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_app_event_path(@event) %> |
<%= link_to 'Back', app_events_path %>

<% content_for :page_name, 'view.posts' %>