config/routes.rb
Rails.application.routes.draw do

  root to:"starter#index"
  resources :starter, only: [:index, :new, :create]
  resources :users

  # Application routes
  namespace :app do
    root to: "dashboard#index"
    get '/login', to: "sessions#new", as: :login
    post '/login', to: "sessions#create"
    get 'profil', to: "sessions#show", as: :profil
    post 'logout', to: "sessions#destroy", as: :logout

    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'settings', to: 'settings#edit', as: :settings
    patch 'settings', to: 'settings#update'

    resources :posts, :events
    resources :connecteds, only: [:index, :create, :update, :destroy]
    resources :collects do
      member do
        post "contribute", to: "collects#contribute", as: :contribution
      end
    end
    
    
    resources :children
    # Group and members
    resources :groups do
      member do
        post "add-members", to: "groups#add_members", as: :add_members_to
        get "eject-member/:user_id", to: "groups#eject_member", as: :eject_member_from
      end
    end
    
    resources :faithfuls do
      member do
        get "approve", to: "faithfuls#approve", as: :approve
        get "eject", to: "faithfuls#eject", as: :eject
      end
    end
  end


  # faithful user routes
  namespace :me, only: [:index, :show, :update] do
    root to: 'posts#index'
    resources :posts do
      member do
        patch 'like', to: "posts#like", as: :like
        patch 'comment', to: 'posts#comment', as: :comment
        patch 'favorite', to: 'posts#favorite', as: :favorite
      end
    end
    get '/calendar', to: 'posts#calendar', as: :calendar
    get '/favorites', to: 'posts#favorites', as: :favorites

    resources :groups, only: [:show, :update]
  end


  namespace :admin do
    resources :churches
  end


  mount Pwa::Engine, at: ''

end

app/models/app/post.rb
class App::Post < Post
  before_create :add_type
  default_scope { where(mark: Post.marks[:post]) }

  # private
  def add_type
    mark = Post.marks[:post]
  end
end

app/models/me/post.rb
class Me::Post < Post

end

app/models/post.rb
class Post < ApplicationRecord
  
  # attr_accessor :marks
  # validates :thumb, presence: true

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :child
  # Association de contribution
  has_many :contributions
  has_many :faithfuls, class_name: "User", foreign_key: "faithful_id", through: :contributions

  # Association likes
  has_many :likes
  has_many :faithfuls, class_name: "User", foreign_key: "user_id", through: :likes

  # association comments
  has_many :comments
  has_many :faithfuls, class_name: "User", foreign_key: "user_id", through: :comments

  # association favorites
  has_many :favorites
  has_many :faithfuls, class_name: "User", foreign_key: "user_id", through: :favorites
  
  enum mark: { post: 1, event: 2, collecte: 3 }
  enum status: {all_post: 1, church_post: 2, group_post: 3, private_post: 4 }
  enum state: { show_post: 1, hide_post: 2 }
  mount_uploader :thumb, ThumbUploader

  scope :mark_post, -> { where(:mark => marks[:post])}
  scope :mark_event, -> { where(:mark => marks[:event])}
  scope :mark_collect, -> { where(:mark => marks[:collecte])}
  scope :filtered, ->(type) { where(:mark => type ) unless type.nil? }

end

app/controllers/app/posts_controller.rb
class App::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = current_user.managed_child.posts.mark_post
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = App::Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = App::Post.new(post_params )
    @post.author = current_user
    @post.child = current_user.managed_child

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = App::Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:app_post).permit(:title, :content, 
        :thumb, :thumb_cache )
    end
end

app/controllers/me/posts_controller.rb
class Me::PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :like, :comment, 
    :favorite]
  def index
    @posts = Me::Post.order(id: :DESC).filtered(params[:type])
  end

  def show
  end

  def update
  end

  def like
    like = @post.likes.where(faithful: current_user).first
    liked = false
    unless like.present?
      @post.likes << Like.new(faithful: current_user)
      liked = true;
    else
      liked = !like.liked
      like.update_columns(liked: !like.liked)
    end
    ActionCable.server.broadcast('post', {
      action: "like",
      post: {
        id: @post.id
      },
      count: @post.likes.liked.size,
      liker: {
        id: like.faithful.id,
        fullname: like.faithful.fullname,
        firstname: like.faithful.firstname,
        lastname: like.faithful.lastname
      },
      message: ""
    })
    render json: {liked: liked}
  end

  def comment
    comment = Comment.new(faithful: current_user, content: params[:comment])
    @post.comments << comment
    # redirect_to me_post_path(@post)
    ActionCable.server.broadcast("post", {
      action: "comment",
      post: {
        id: @post.id
      },
      count: @post.comments.liked.size,
      liker: {
        id: comment.faithful.id,
        fullname: comment.faithful.fullname,
        firstname: comment.faithful.firstname,
        lastname: comment.faithful.lastname
      },
      html: ApplicationController.render(partial: 'me/ui/explorer/single_comment', locals: {
        comment: comment
      }),
      message: ""
    })
    render json: {post: params}
  end

  def favorite
    favorite = @post.favorites.where(faithful: current_user).first
    liked = false
    unless favorite.present?
      favorite = Favorite.new(faithful: current_user)
      @post.favorites << favorite
      liked = true;
    else
      liked = !favorite.liked
      favorite.update_columns(liked: !favorite.liked)
    end
    ActionCable.server.broadcast("post", {
      action: "favorite",
      post: {
        id: @post.id
      },
      count: @post.favorites.liked.size,
      liker: {
        id: favorite.faithful.id,
        fullname: favorite.faithful.fullname,
        firstname: favorite.faithful.firstname,
        lastname: favorite.faithful.lastname
      },
      html: "",
      message: ""
    })
    render json: {liked: liked}
  end

  def favorites
    @posts = current_user.favorites.liked
  end

  def calendar
    # @posts = current_user
  end

  private
  def set_post
    @post = Me::Post.find(params[:id])
  end
end

app/views/app/posts/_form.html.erb
<%= form_for post do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= form.label :thumb, "Image en avant" %>
    <%= form.file_field :thumb, class: "form-control", required: true %>
    <%= form.hidden_field :thumb_cache %>
  </div>

  <div class="mt-2 ">
    <%= image_tag post.thumb.thumb.url, alt: 'thumbnail' if post.thumb %>
  </div>

  <div class="text-right mt-3">
    <%= form.submit "Sauvegarder", class: "btn btn-primary text-white" %>
  </div>
<% end %>

<% content_for :page_name, 'view.posts' %>

app/views/app/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', app_posts_path %>

app/views/app/posts/index.html.erb
<div class="card">
  <div class="card-header">
    <h3>Liste des Publications</h3>
  </div>
  <div class="card-body">
    <div class="row text-right">
      <div class="col-12">
        <%= link_to 'Nouvelle Publication', new_app_post_path, data: {turbolinks: false}, class: 'btn btn-primary btn-sm text-white mb-2' %>
      </div>
    </div>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Titre</th>
          <th>Contenue</th>
          <th>Auteur</th>
          <th>Créé</th>
          <th></th>
        </tr>
      </thead>
      
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title.truncate(100) %></td>
            <td><%= post.content.truncate(200) %></td>
            <td><%= post.author.present? ? post.author.fullname : 'Aucun'%></td>
            <td><%=str_time(post.created_at) %></td>
            <td>
              <%= link_to content_tag('i', 'Voir', class: "fa fa-eye"), app_post_path(post), class: 'btn btn-success btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Editer', class: "fa fa-pen"), edit_app_post_path(post), class: 'btn btn-primary btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Supprimer', class: "fa fa-trash"), app_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs text-white mb-2' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>


<% content_for :page_name, 'view.posts' %>

app/views/app/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', app_posts_path %>

app/views/app/posts/show.html.erb
<div class="card card-success">
  <div class="card-body">
    <div class="row">
      <div class="offset-lg-1 offset-xl-2 col-md-12 col-lg-10 col-xl-8">
        <div class="card mb-2 bg-gradient">
          <img class="card-img-top" src="<%= @post.thumb? ?  @post.thumb.thumbnail.url : asset_url('/templates/adminLte/img/event.jpeg')  %>" alt="Dist Photo 1">
          <div class="card-img-overlay d-flex flex-column justify-content-end">
            <h5 class="card-title text-primary text-white"> <%= @post.title %> </h5>
            <a href="#" class="text-white"> </a>
            <small class="card-text text-white pb-2 pt-1 text-right"><%= "Par #{@post.author.fullname} #{str_time(@post.created_at)}" %></small>
          </div>
        </div>
        <div class="card-body">
          <%= markdown(@post.content) %>
        </div>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_app_post_path(@post) %> |
<%= link_to 'Back', app_posts_path %>

<% content_for :page_name, 'view.posts' %>