config/routes.rb
Rails.application.routes.draw do

  root to:"starter#index"
  resources :starter, only: [:index, :new, :create]
  resources :users

  # Application routes
  namespace :app do
    root to: "dashboard#index"
    get '/login', to: "sessions#new", as: :login
    post '/login', to: "sessions#create"
    get 'profil', to: "sessions#show", as: :profil
    post 'logout', to: "sessions#destroy", as: :logout

    get 'dashboard', to: "dashboard#index", as: :dashboard
    get 'settings', to: 'settings#edit', as: :settings
    patch 'settings', to: 'settings#update'

    resources :posts, :events
    resources :connecteds, only: [:index, :create, :update, :destroy]
    resources :collects do
      member do
        post "contribute", to: "collects#contribute", as: :contribution
      end
    end
    
    
    resources :children
    # Group and members
    resources :groups do
      member do
        post "add-members", to: "groups#add_members", as: :add_members_to
        get "eject-member/:user_id", to: "groups#eject_member", as: :eject_member_from
      end
    end
    
    resources :faithfuls do
      member do
        get "approve", to: "faithfuls#approve", as: :approve
        get "eject", to: "faithfuls#eject", as: :eject
      end
    end
  end


  # faithful user routes
  namespace :me, only: [:index, :show, :update] do
    root to: 'posts#index'
    resources :posts do
      member do
        patch 'like', to: "posts#like", as: :like
        patch 'comment', to: 'posts#comment', as: :comment
        patch 'favorite', to: 'posts#favorite', as: :favorite
      end
    end
    get '/calendar', to: 'posts#calendar', as: :calendar
    get '/favorites', to: 'posts#favorites', as: :favorites

    resources :groups, only: [:show, :update]
  end


  namespace :admin do
    resources :churches
  end


  mount Pwa::Engine, at: ''

end

app/models/app/faithful.rb
class App::Faithful < User
  attr_accessor :child_id
  after_create :generate_matricule

  private
  def generate_matricule
    self.update_columns(matricule: "#{id}")
  end
end

app/controllers/app/faithfuls_controller.rb
class App::FaithfulsController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy, :approve, :eject ]
  def index
    @faithfuls = current_user.managed_child.faithfuls
  end

  def new
    @faithful = App::Faithful.new
  end

  def create
    @faithful = App::Faithful.new(user_params)
    @child = current_user.managed_child
    
    if @faithful.save(validate: false)
      @child.faithfuls << @faithful
      redirect_to app_faithful_path(@faithful.id), notice: "faithful created"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    params = user_params
    if @faithful.update_columns( 
      firstname: params["firstname"], 
      lastname: params["lastname"],
      email: params["email"],
      phone: params["phone"],
      profession: params["profession"],
    )
      redirect_to app_faithful_path(@faithful.id), notice: "faithful updated"
    else
      render :edit
    end
  end

  def approve
    @faithful.update_columns(approved: true)
    redirect_to app_faithfuls_path, notice: "Fidele approuvé avec succes"
  end

  def eject
    
    @faithful.childs.last.faithfuls.delete(@faithful)
    @faithful.update_columns(approved: false)
    redirect_to app_faithfuls_path, notice: "Fidele ejecté avec succes"
  end

  def destroy
    @faithful.destroy
    redirect_to app_faithfuls_path, notice: "faithful deleted"
  end

  private
  def set_user
    @faithful = App::Faithful.childs.find(params[:id])
  end

  def user_params
    params.require(:app_faithful).permit(:phone, :email, :firstname, :lastname,
    :profession, :approved)
  end
end

app/views/app/faithfuls/_form.html.erb
<%= form_for faithful do |f| %>
  <% if faithful.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faithful.errors.count, "error") %> prohibited this app_child from being saved:</h2>

      <ul>
      <% faithful.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control", required: false %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.phone_field :phone, class: "form-control", required: true %>
  </div>

  <div class="field">
    <%= f.label :profession %>
    <%= f.text_field :profession, class: "form-control", required: true %>
  </div>

  <%= f.check_box :approved, checked: true, hidden: true %>

  <!-- <div class="form-group"> -->
    <% # f.label :child_id, "Station" %>
    <% # f.select :child_id, options_for_select(current_user.managed_child.church.childs.map{|c| [c.name, c.id]}, selected: @faithful.childs.present? ? @faithful.childs.last.id : 0), {include_blank: true, required: true}, {class: "form-control"} %>
  <!-- </div> -->

  <div class="text-right">
    <%= f.submit 'Sauvegarder', class: "btn btn-primary btn-sm" %>
  </div>

<% end %>

app/views/app/faithfuls/edit.html.erb
<h1>Edit faithful</h1>
<%= render 'form', faithful: @faithful %>
<%= link_to 'Back', app_faithfuls_path %>

<% content_for :page_name, 'view.faithfuls' %>

app/views/app/faithfuls/index.html.erb
<div class="card">
  <div class="card-header">
    <h3>  </h3>
    <%= content_tag 'h3', "Liste des fidèles" %>
  </div>
  <div class="card-body">
    <div class="row text-right">
      <div class="col-12">
        <%= link_to 'Nouveau Fidèle', new_app_faithful_path, data: {turbolinks: false}, class: 'btn btn-primary btn-sm text-white mb-2' %>
      </div>
    </div>
    <table id="faithfulList" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Téléphone</th>
          <th>Profession</th>
          <th>Groupes</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @faithfuls.each do |f| %>
          <tr>
            <td> <%= f.id %> </td>
            <td> <%= f.firstname %> </td>
            <td> <%= f.lastname %> </td>
            <td> <%= f.phone %> </td>
            <td> <%= f.profession %> </td>
            <td> 
            <% f.groups.each do |g| %>
              <%= link_to g.name, app_group_path(g), class: 'btn btn-link' %>               
            <% end %>
            </td>
            <td>  
              <%= link_to content_tag('i', 'Approuver', class: "fa fa-check"), approve_app_faithful_path(f), data: { confirm: 'Are you sure?' }, class: "btn btn-success btn-xs text-white mb-2 #{'disabled ' if f.approved? }" %>
              <%= link_to content_tag('i', 'Ejecter', class: "fa fa-close"), eject_app_faithful_path(f), data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs text-white mb-2" %>
              <%= link_to content_tag('i', 'Voir', class: "fa fa-eye"), f, class: 'btn btn-success btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Editer', class: "fa fa-pen"), edit_app_faithful_path(f), class: 'btn btn-primary btn-xs text-white mb-2' %>
              <%= link_to content_tag('i', 'Supprimer', class: "fa fa-trash"), f, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs text-white mb-2' %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>





<% content_for :page_name, 'view.faithfuls' %>

<% content_for :styles do%>
  
<% end %>


<% content_for :script do%>

  <script>
    $('#faithfulList').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  </script>
<% end %>

app/views/app/faithfuls/new.html.erb
<h1>New faithful</h1>
<%= render 'form', faithful: @faithful %>
<%= link_to 'Back', app_faithfuls_path %>

<% content_for :page_name, 'view.faithfuls' %>

app/views/app/faithfuls/show.html.erb
<h1>App::Faithfuls#show</h1>
<p>Find me in app/views/app/faithfuls/show.html.erb</p>


<% content_for :page_name, 'view.faithfuls' %>